# Gaussian Elimination

## Question 1
#### Code the echelon form method and use it to reduce matrices to echelon form

In [49]:
import matplotlib.pyplot as plt 
import numpy as np
import string

In [50]:
rowlist = np.array([[0,2,3,4,5],[0,0,0,3,2],[1,2,3,4,5],[0,0,0,6,7],[0,0,0,9,9]])

In [51]:
print(rowlist)

[[0 2 3 4 5]
 [0 0 0 3 2]
 [1 2 3 4 5]
 [0 0 0 6 7]
 [0 0 0 9 9]]


In [52]:
new_rowlist=[]
rows_left = set(range(len(rowlist)))
print(rows_left)

{0, 1, 2, 3, 4}


In [53]:
col_label_list=list(rows_left)
print(col_label_list)

[0, 1, 2, 3, 4]


In [54]:
for c in col_label_list:
    rows_with_nonzero = [r for r in rows_left if rowlist[r][c]!=0]
    if rows_with_nonzero!=[]:
        pivot = rows_with_nonzero[0]
        new_rowlist.append(rowlist[pivot])
        rows_left.remove(pivot)

In [55]:
new_rowlist=np.array(new_rowlist)
print(new_rowlist)

[[1 2 3 4 5]
 [0 2 3 4 5]
 [0 0 0 3 2]
 [0 0 0 6 7]]


In [56]:
new_rowlist=[]
rows_left = set(range(len(rowlist)))
print(rows_left)
col_label_list=list(rows_left)
print(col_label_list)

for c in col_label_list:
    rows_with_nonzero = [r for r in rows_left if rowlist[r][c]!=0]
    if rows_with_nonzero!=[]:
        pivot = rows_with_nonzero[0]
        rows_left.remove(pivot)
        new_rowlist.append(rowlist[pivot])
        for r in rows_with_nonzero[1:]:
            multiplier=rowlist[r][c]/rowlist[pivot][c]
            rowlist[r] = rowlist[r]- multiplier*rowlist[pivot]

{0, 1, 2, 3, 4}
[0, 1, 2, 3, 4]


In [57]:
new_rowlist=np.array(new_rowlist) 
print(new_rowlist)

[[1 2 3 4 5]
 [0 2 3 4 5]
 [0 0 0 3 2]
 [0 0 0 0 3]]


## Question 2
#### Perform Gaussian Elimination 

In [58]:
import sympy as sp

In [59]:
rowlist = np.array([[0,2,3,4,5],[0,0,0,3,2],[1,2,3,4,5],[0,0,0,6,7],[0,0,0,9,9]])

In [60]:
reduced_rowlist=sp.Matrix(rowlist).rref()
print(reduced_rowlist)

(Matrix([
[1, 0,   0, 0, 0],
[0, 1, 3/2, 0, 0],
[0, 0,   0, 1, 0],
[0, 0,   0, 0, 1],
[0, 0,   0, 0, 0]]), (0, 1, 3, 4))


#### Since row 4 has 0 $\times$ X4=1. There is no solution.