# Orthogonalization and Orthonormalization

In [7]:
import numpy as np
import scipy.linalg   # SciPy Linear Algebra Library

## Question 1
#### Write a program to test if a set of vectors {v1,v2,...,vn} is an orthogonal set

In [9]:
# Taking column vectors
v1 = [[-6, -1, 3, 6, 2, -3, -2, 1]]
v2 = [[-3, 2, 6, -3, -1, 6, -1, 2]]
v3 = [[6, 1, 3, 6, 2, 3, 2, 1 ]]
v4 = [[1, -6, -2, -1, 3, 2, -3, 6]]
   
# Transpose of vectors
transposeOfV1 = np.transpose(v1)
transposeOfV2 = np.transpose(v2)
transposeOfV3 = np.transpose(v3)
transposeOfV4 = np.transpose(v4)
   
# Matrix multiplication of both vectors
resultv1v2 = np.dot(v2, transposeOfV1)
print("Result  = ", resultv1v2)
resultv1v3 = np.dot(v3, transposeOfV1)
print("Result  = ", resultv1v3)
resultv1v4 = np.dot(v4, transposeOfV1)
print("Result  = ", resultv1v4)
resultv2v3 = np.dot(v2, transposeOfV3)
print("Result  = ", resultv2v3)
resultv2v4 = np.dot(v2, transposeOfV4)
print("Result  = ", resultv2v4)
resultv3v4 = np.dot(v3, transposeOfV4)
print("Result  = ", resultv3v4)

Result  =  [[0]]
Result  =  [[0]]
Result  =  [[0]]
Result  =  [[0]]
Result  =  [[0]]
Result  =  [[0]]


##### All column vectors are orthogonal to each other

## Question 1(b)
#### Is it always true (in executing program on dot product) that 2 vectors v.w ≠ 0 means v is not orthogonal to w? If it is not necessary true, give an example and propose a fix.

##### Yes

## Question 2
#### Write a module “Orthonormalisation” that defines a a procedure orthonormalise(L) with the following specs:
#### • Input: a list L of linearly independent Vecs
#### • Output: a list L* of len(L) orthonormal Vecs such that, for i= 1,2,..., len(L), the first i Vecs of L* and the first i Vecs of L span the same space.

In [13]:
def gram_schmidt(X):
    """
    Implements Gram-Schmidt orthogonalization.

    Parameters
    ----------
    X : an n x k array with linearly independent columns

    Returns
    -------
    U : an n x k array with orthonormal columns

    """

    # Set up
    n, k = X.shape
    U = np.empty((n, k))
    I = np.eye(n)

    # The first col of U is just the normalized first col of X
    v1 = X[:,0]
    U[:, 0] = v1 / np.sqrt(np.sum(v1 * v1))

    for i in range(1, k):
        # Set up
        b = X[:, i]       # The vector we're going to project
        Z = X[:, 0:i]     # First i-1 columns of X

        # Project onto the orthogonal complement of the col span of Z
        M = I - Z @ np.linalg.inv(Z.T @ Z) @ Z.T
        u = M @ b

        # Normalize
        U[:, i] = u / np.sqrt(np.sum(u * u))

    return U

In [14]:
vector =[[4,3,1,2], 
        [8,9,-5,-5], 
        [10,1,-1,5]]

gram_schmidt(np.array(vector))

array([[ 0.2981424 ,  0.1407365 ,  0.94408916, -0.05373607],
       [ 0.59628479,  0.74487369, -0.29934534,  0.55079474],
       [ 0.74535599, -0.65219355, -0.13815939, -0.83290911]])

In [15]:
A = np.array([[0, 1], [1, 1], [1, 1], [2, 1]])
b = np.array([1, 0, 2, 1])
q, r = np.linalg.qr(A)
p = np.dot(q.T, b)
np.dot(np.linalg.inv(r), p)
np.array([  1.1e-16,   1.0e+00])

array([1.1e-16, 1.0e+00])

## Question 3
#### Write a program to compute the QR factorization of matrix A = QR, where Q is orthonormal and R is upper triangular. (refer to lecture notes for the theory). You may assume A consists of linearly independent vectors. Compute the QR factorization of A, formed by the 3 column vectors in Q2.

In [6]:
A = np.array([[0, 1], [1, 1], [1, 1], [2, 1]])
q, r = np.linalg.qr(A)

print("Q:")
print(q)
print()
print("R:")
print(r)

Q:
[[ 0.          0.8660254 ]
 [-0.40824829  0.28867513]
 [-0.40824829  0.28867513]
 [-0.81649658 -0.28867513]]

R:
[[-2.44948974 -1.63299316]
 [ 0.          1.15470054]]
